Controllers/EmployeesController.cs
using AgriApp.Models;
using AgriApp.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AgriApp.Controllers
{
    [Authorize(Roles = "Employee")]
    public class EmployeesController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly AuthDbContext dbContext;

        public EmployeesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, AuthDbContext dbContext)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> ViewFarmers()
        {
            var farmers = await userManager.GetUsersInRoleAsync("Farmer");
            return View(farmers);
        }

        [HttpGet]
        public async Task<IActionResult> ViewProducts(string id, string str)
        {
            //var products = await dbContext.Products.Where(prd => prd.FarmerId == id).ToListAsync();

            IQueryable<Product> query = dbContext.Products.Where(prd => prd.FarmerId == id);
            
            var farmer = await userManager.FindByIdAsync(id);
            ViewBag.FarmerEmail = farmer?.Email;
            ViewBag.FarmerId = id;

            if (string.IsNullOrEmpty(str))
            {
                // no filter
            }
            else if (str == "Name")
            {
                query = query.OrderBy(prd => prd.Name);
            }
            else if (str == "Date")
            {
                query = query.OrderBy(prd => prd.Date);
            }
            else if (str == "Category")
            {
                query = query.OrderBy(prd => prd.Category);
            }


            var products = await query.ToListAsync();

            

            return View(products);
        }
    }
}

Controllers/FarmersController.cs
using AgriApp.Models;
using AgriApp.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AgriApp.Controllers
{
    [Authorize(Roles = "Farmer")]
    public class FarmersController : Controller
    {
        private readonly AuthDbContext dbContext;
        private readonly UserManager<IdentityUser> userManager;

        public FarmersController(AuthDbContext dbContext, UserManager<IdentityUser> userManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddProductViewModel viewModel)
        {
            var farmerID = userManager.GetUserId(User);
            var product = new Product
            {

                Name = viewModel.Name,
                Category = viewModel.Category,
                FarmerId = farmerID,
                Date = DateTime.Now,

            };

            await dbContext.Products.AddAsync(product);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List(string str)
        {
            var farmerID = userManager.GetUserId(User);

            IQueryable<Product> query = dbContext.Products.Where(prd => prd.FarmerId == farmerID);

            if (string.IsNullOrEmpty(str))
            {
                // no filter
            }
            else if(str == "Name")
            {
                query = query.OrderBy(prd => prd.Name);
            }
            else if (str == "Date")
            {
                query = query.OrderBy(prd => prd.Date); 
            }
            else if (str == "Category")
            {
                query = query.OrderBy(prd => prd.Category);
            }


            var product = await query.ToListAsync();

            return View(product);
        }

       
    }
}

Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgriApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgriApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Agri-Energy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @if(User.IsInRole("Farmer")){
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Farmers" asp-action="List">My Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Farmers" asp-action="Add">Add Product</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav d-flex justify-content-end">
                                <li>
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        else if(User.IsInRole("Employee")){
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Register">Add Farmer</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="ViewFarmers">Farmers</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav d-flex justify-content-end">
                                <li>
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                            </li>
                               
                        </ul>
                        <ul class="navbar-nav d-flex justify-content-end">
                            <li class="nav-item">
                                <a asp-page="/Login" class="btn btn-primary">Login</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2025 - AgriApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>