ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AgriApp.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public String Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public String Password { get; set; }
       
        public bool RememberMe { get; set; }
    }
}

ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace AgriApp.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public String Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public String Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password did not match")]
        public String ConfirmPassword { get; set; }
    }
}

Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Login.cshtml.cs
using AgriApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public Login Model  { get; set; }

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
               var identityResult = await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                if (identityResult.Succeeded) 
                { 
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }

                }

                ModelState.AddModelError("", "Username or Password incorrect");

            }

            return Page();
        }
    }
}

Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }


    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/Register.cshtml.cs
using AgriApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AgriApp.Pages
{
    [Authorize(Roles = "Employee")]
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public Register Model { get; set; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email = Model.Email
                };

                var result = await userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user, "Farmer");
                    //await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Login");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return Page();
        }
    }
}

Pages/About.cshtml
@page
@model AgriApp.Pages.AboutModel
@{
}
<style>
    body {
        background-color: #050428;
    }
</style>
<div class="about-body">

    <div class="about-sec2">
        <h1>About Us</h1>
        <div class="as2-text">
        <p>
            This is the official website for Agri-Energy. 
            This web application was created to provide members of the agriculture field and 
            ecofriendly energy technology providers with a central hub where they can exchange 
            ideas and best practices, communicate with ecofriendly energy technology providers, 
            access learning resources, farmers and ecofriendly energy technology professionals 
            to cooperate, and provide information on financial support for ecofriendly 
            initiatives.
        </p>
        </div>
    </div>

    <div class="about-sec1">
        <img src="~/images/agrilogo.png" />
        <div class="as1-text">
            <h1>Agri-Energy</h1>
            <p>Ecofriendly Agriculture</p>
        </div>
    </div>

</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<style>
    body{
        background-color: #050428;
    }
</style>

<div class="home-body">
    <div class="home-sec1">
        <img src="~/images/agrilogo.png" />
        <div class="hs1-text">
            <h1>Agri-Energy</h1>
            <p>Ecofriendly Agriculture</p>
        </div>
    </div>
    
</div>

Pages/Login.cshtml
@page
@model AgriApp.Pages.LoginModel
@{
}
<dv class="add-body">

    <div class="ab-para">
        <h1>Login </h1>
        <h2>Form for users to login</h2>
        <p>
            Ensure that all fields are entered
        </p>
    </div>

    <form method="post" class="add-form">
        <div class="form-section">
            
            <input placeholder="Email Address" type="text" asp-for="Model.Email" class="form-control" required />
            <span asp-validation-for="Model.Email" class="text-danger"></span>
        </div>
        <div class="form-section">
            
            <input placeholder="Password" type="password" asp-for="Model.Password" class="form-control" required />
            <span asp-validation-for="Model.Password" class="text-danger"></span>
        </div>
        <div class="form-section">
            
            <label class="form-label" asp-for="Model.RememberMe">Remember Me?</label>
        </div>
        <div class="form-section">
            <button type="submit" class="btn-submit">Login</button>
        </div>
    </form>

</dv>

         
        

Pages/Logout.cshtml
@page
@model AgriApp.Pages.LogoutModel
@{
}

<div class="logout-container">


    <form method="post">

        <div class="logout-div">
            <p>Are you sure you want to logout?</p>
            <p>
                <button class="" asp-page-handler="Logout"> Yes</button>
                <button class="" asp-page-handler="DontLogout">No</button>
            </p>

        </div>


    </form>

</div>

Pages/Register.cshtml
@page
@model AgriApp.Pages.RegisterModel
@{
}

<div class="add-body">
    <div class="ab-para">
        <h1>Register Farmer</h1>
        <h2>Form for Employees to register farmers</h2>
        <p>
            Ensure that all fields are entered
        </p>
    </div>

    <form method="post" class="add-form">
        <div asp-validation-summary="All" class="text-danger">
        </div>
        <div class="form-section">
            
            <input placeholder="Email Address" type="text" asp-for="Model.Email" class="form-control" required />
            <span asp-validation-for="Model.Email" class="text-danger"></span>
        </div>
        <div class="form-section">
            
            <input placeholder="Password" type="password" asp-for="Model.Password" class="form-control" required />
            <span asp-validation-for="Model.Password" class="text-danger"></span>
        </div>
        <div class="form-section">
            
            <input placeholder="Confirm Password" type="password" asp-for="Model.ConfirmPassword" class="form-control" required />
            <span asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
        </div>
        <div class="form-section">
            <button type="submit" class="btn-submit">Register</button>
        </div>
    </form>

</div>